// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvupKo8Wvj69nX9CxA5ACfVcxy4uNXvo',
    appId: '1:1050167267665:web:f1ec402dc21f2e86a94370',
    messagingSenderId: '1050167267665',
    projectId: 'koperasi-undiksha',
    authDomain: 'koperasi-undiksha.firebaseapp.com',
    storageBucket: 'koperasi-undiksha.appspot.com',
    measurementId: 'G-KJ00W022YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2pOLeZEBLPLGtx-1348i0q_g8_DjLaGs',
    appId: '1:1050167267665:android:89452013c5671bb6a94370',
    messagingSenderId: '1050167267665',
    projectId: 'koperasi-undiksha',
    storageBucket: 'koperasi-undiksha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5WTifFvKzeXD4j5-q6Z7rH7XK4cvOaU',
    appId: '1:1050167267665:ios:ebc27c4496fd9862a94370',
    messagingSenderId: '1050167267665',
    projectId: 'koperasi-undiksha',
    storageBucket: 'koperasi-undiksha.appspot.com',
    iosClientId: '1050167267665-483a4oj2a8n5qe8sg3k549ehks4jpfi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.koperasiUndiksha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5WTifFvKzeXD4j5-q6Z7rH7XK4cvOaU',
    appId: '1:1050167267665:ios:ebc27c4496fd9862a94370',
    messagingSenderId: '1050167267665',
    projectId: 'koperasi-undiksha',
    storageBucket: 'koperasi-undiksha.appspot.com',
    iosClientId: '1050167267665-483a4oj2a8n5qe8sg3k549ehks4jpfi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.koperasiUndiksha',
  );
}
